version: '3.4'

name: templates-api
services:
  seq:
    image: datalust/seq:latest
    container_name: seq
    ports:
      - "45341:45341"
      - "5341:5341"
      - "8081:80"
      - "8443:443"
    environment:
      ACCEPT_EULA: Y
  postgres:
    image: postgres:latest
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: templates